#
# This is makefile for ' sleep_test/usleep '.
#
# Read more on www.orange-engineer.com
#
# (c) Jacek Pierzchlewski, 2017  jacek@pierzchlewski.com
# license: BSD-2-Clause. 

# usleep(1) tests
us_test: us_test.cpp
	g++ us_test.cpp -o us_test
us_testc: us_test.c
	gcc us_test.c -o us_testc



